
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\kavna\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://orgb7665afa.api.crm.dynamics.com" /namespace:"Kev.Xrm.EntityWrappers" /out:"C:\Users\kavna\Desktop\Javista\Part Time\Day 1\OptionSets.cs" /SuppressGeneratedCodeAttribute /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" 
//------------------------------------------------------------------------------

namespace Kev.Xrm.EntityWrappers
{


    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_AccountCategoryCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreferredCustomer = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Standard = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_AccountClassificationCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_AccountRatingCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_Address1_AddressTypeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        BillTo = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Primary = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ShipTo = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_Address1_FreightTermsCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        FOB = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoCharge = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_Address1_ShippingMethodCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Airborne = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DHL = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        FedEx = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        FullLoad = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        PostalMail = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        UPS = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        WillCall = 7,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_Address2_AddressTypeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_Address2_FreightTermsCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_Address2_ShippingMethodCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_BusinessTypeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_CustomerSizeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_CustomerTypeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Competitor = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Consultant = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Customer = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Influencer = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Investor = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 12,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Partner = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Press = 7,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Prospect = 8,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reseller = 9,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Supplier = 10,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vendor = 11,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_IndustryCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        FilmProductionCompanies = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        NewsNetworks = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        PodcastProduction = 7,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        RadioStations = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        StreamingPlatforms = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        TelevisionProduction = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        TVStations = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_OwnershipCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Private = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Public = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Subsidiary = 3,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_PaymentTermsCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        _210Net30 = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Net30 = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Net45 = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Net60 = 4,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_PreferredAppointmentDayCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friday = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Monday = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Saturday = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sunday = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Thursday = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tuesday = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wednesday = 3,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_PreferredAppointmentTimeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Afternoon = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Evening = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Morning = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_PreferredContactMethodCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Any = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fax = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mail = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Phone = 3,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_ShippingMethodCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_StatusCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Account_TerritoryCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_AccountRoleCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DecisionMaker = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Employee = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Influencer = 3,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_Address1_AddressTypeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        BillTo = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Primary = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ShipTo = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_Address1_FreightTermsCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        FOB = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoCharge = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_Address1_ShippingMethodCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Airborne = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DHL = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        FedEx = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        FullLoad = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        PostalMail = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        UPS = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        WillCall = 7,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_Address2_AddressTypeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_Address2_FreightTermsCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_Address2_ShippingMethodCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_Address3_AddressTypeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_Address3_FreightTermsCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_Address3_ShippingMethodCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_CustomerSizeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_CustomerTypeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_EducationCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_FamilyStatusCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Divorced = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Married = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Single = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Widowed = 4,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_GenderCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_HasChildrenCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_LeadSourceCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_PaymentTermsCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        _210Net30 = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Net30 = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Net45 = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Net60 = 4,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_PreferredAppointmentDayCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friday = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Monday = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Saturday = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sunday = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Thursday = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tuesday = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wednesday = 3,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_PreferredAppointmentTimeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Afternoon = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Evening = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Morning = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_PreferredContactMethodCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Any = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fax = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mail = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Phone = 3,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_ShippingMethodCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_StatusCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum Contact_TerritoryCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum powerpagelanguages
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Arabic = 1025,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        BasqueBasque = 1069,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        BulgarianBulgaria = 1026,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CatalanCatalan = 1027,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChineseChina = 2052,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChineseHongKongSAR = 3076,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChineseTraditional = 1028,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CroatianCroatia = 1050,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CzechCzechRepublic = 1029,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DanishDenmark = 1030,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DutchNetherlands = 1043,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        English = 1033,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        EstonianEstonia = 1061,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        FinnishFinland = 1035,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        FrenchFrance = 1036,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        GalicianSpain = 1110,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        GermanGermany = 1031,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreekGreece = 1032,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hebrew = 1037,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        HindiIndia = 1081,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        HungarianHungary = 1038,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        IndonesianIndonesia = 1057,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ItalianItaly = 1040,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        JapaneseJapan = 1041,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        KazakhKazakhstan = 1087,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        KoreanKorea = 1042,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        LatvianLatvia = 1062,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        LithuanianLithuania = 1063,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        MalayMalaysia = 1086,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Norwegian_BokmlNorway = 1044,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        PolishPoland = 1045,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        PortugueseBrazil = 1046,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        PortuguesePortugal = 2070,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        RomanianRomania = 1048,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        RussianRussia = 1049,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Serbian_CyrillicSerbia = 3098,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Serbian_LatinSerbia = 2074,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SlovakSlovakia = 1051,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SlovenianSlovenia = 1060,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spanish_TraditionalSortSpain = 3082,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SwedishSweden = 1053,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThaiThailand = 1054,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        TurkishTrkiye = 1055,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        UkrainianUkraine = 1058,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        VietnameseVietnam = 1066,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum SystemUser_AccessMode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Administrative = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DelegatedAdmin = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Noninteractive = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Read = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReadWrite = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SupportUser = 3,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum SystemUser_Address1_AddressTypeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum SystemUser_Address1_ShippingMethodCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum SystemUser_Address2_AddressTypeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum SystemUser_Address2_ShippingMethodCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum SystemUser_AzureState
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exists = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notfoundorharddeleted = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Softdeleted = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum SystemUser_CALType
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Administrative = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Basic = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeviceBasic = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeviceEnterprise = 8,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeviceEssential = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeviceProfessional = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enterprise = 7,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Essential = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        FieldService = 11,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Professional = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProjectService = 12,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sales = 9,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Service = 10,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum SystemUser_DeletedState
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notdeleted = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Softdeleted = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum SystemUser_EmailRouterAccessApproval
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Empty = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingApproval = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 3,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum SystemUser_IncomingEmailDeliveryMethod
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ForwardMailbox = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        MicrosoftDynamics365forOutlook = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerSideSynchronizationorEmailRouter = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum SystemUser_InviteStatusCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvitationAccepted = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvitationExpired = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvitationNearExpired = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvitationNotSent = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvitationRejected = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvitationRevoked = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invited = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum SystemUser_OutgoingEmailDeliveryMethod
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        MicrosoftDynamics365forOutlook = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerSideSynchronizationorEmailRouter = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum SystemUser_PreferredAddressCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        MailingAddress = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        OtherAddress = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum SystemUser_PreferredEmailCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultValue = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum SystemUser_PreferredPhoneCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        HomePhone = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        MainPhone = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        MobilePhone = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        OtherPhone = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum appaction_ClientType
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Browser = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mobile = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        MailApp = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum card_Sizes
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Small = 200000000,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Medium = 200000001,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Large = 200000002,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum formmappingallowedoperations
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Create = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    public enum msdyn_knowledgemanagementsetting_msdyn_actionlist
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Linkunlinkarticle = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CopyURL = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        LinkarticleandemailURL = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Linkarticleandsendarticlecontent = 3,
    }
}
